### ISSUE TITLE
Fail to access the share from anywhere

### ISSUE THREAD

**Issue by raphaelcasimir** [dperson/samba#108]
Hello,
Thanks for your work on this container.
Unfortunately, I spent 3 hours trying to get it working with no success. I have an empty server (no samba services running) with an empty Docker wired to my network. Even with the provided example I get nothing. The container is running, but no client, windows or Linux sees any shares. I also tried to add -w "WORKGROUP" with no success either.

And the majority of containers from others don't work either, it may be a problem in a Docker update... I got one working for a moment but the container crashed after a few minutes...
If you have an idea, please tell...

**Comment by htkoca** [comment]
OS? What is the command you ran? Details please :)

**Comment by dperson** [comment]
@raphaelcasimir like @htkoca  said, without further details on your OS (client and server) / network layout / VM or hardware / the docker command you ran and it's logs it's near impossible to narrow down where your problem is.

Feel free to reopen or reply to this issue with more details and I'll look into it, but for now I'm closing it.

**Comment by raphaelcasimir** [comment]
Hello, didn't have much time to complete the issue, sorry. So I was running docker on Ubuntu Server 16.04, and I tried to access the share via linux SMB on 17.10, and Win10 with no success. I abandoned SMB now.
