### ISSUE TITLE
heads up, samba 4.8 

### ISSUE THREAD

**Issue by gonewest818** [dperson/samba#130]
I know you aren't supporting samba 4.8 until it's released out of edge, but I just tried building this image locally with the Dockerfile adjusted to `FROM alpine:edge`.  In my tweaked image I'm seeing `samba.sh` fails to launch and prints the error:

      exit_daemon: STATUS=daemon failed to start: Failed to create session, error code 1

But running `smbd` by hand in the container works fine. After some trial and error I have a hunch this commit is the culprit. https://github.com/samba-team/samba/commit/af38d73b06c0c40ef59c2ffe0fc6580b0787b7d0#diff-5c2ad073c5b09e8c83a6ec1160774dfaR376

Under the hood you can see the samba team implements the process group creation like this: `setpgid((pid_t)0, (pid_t)0);`  And my hunch is that this is the root of the problem, because launching `smbd -FS --no-process-group` disables the `setpgid` and causes Samba 4.8 to launch.

See also: https://github.com/dubiousjim/dcron/issues/13#issuecomment-244043189

**Comment by dperson** [comment]
Thanks for the report, I'll remove the `exec` from the script, as according to the last link you included, not being PID 1 stopped the error from taking place.

**Comment by Strayer** [comment]
Hey @dperson!

Sorry for commenting on a closed issue, but I was just looking at this and know the problems from dcron linked in the original issue. This problem is also worked around by using an init wrapper entrypoint like [tini](https://github.com/krallin/tini).

I'm using tiny in pretty much all my Docker images without problems and it seems to be a good practice anyway. As far as I know samba is starting child processes for connections too, so it would certainly make sense to include an init wrapper.

Are you open for a PR including it?

**Comment by Strayer** [comment]
There are two ways to do this. The way I prefer does require installing tini, it is included in the [Alpine package repository](https://github.com/krallin/tini#alpine-linux-package) though.

The other way is running the container with `docker run --init` (see [Docker docs](https://docs.docker.com/engine/reference/run/#specify-an-init-process)).

I prefer installing it into the image directly – in this case because then one could use exec in the entrypoint again. Using the second way would break the image when using exec for users who don't run the container with --init, as described in the original issue.

**Comment by dperson** [comment]
@Strayer Okay, I've added `tini` to the container and have it calling the original `ENTRYPOINT` script... hopefully not much blows up.

**Comment by Strayer** [comment]
That was quick - thanks! Looks fine to me. I'll hopefully have some time soon to play around with Samba 4.8 from alpine edge for Time Machine using this image, so this helps a lot.

**Comment by gonewest818** [comment]
@Strayer for what it's worth I've started playing around with time machine over here (https://github.com/gonewest818/samba/blob/timemachine/Dockerfile#L28-L39). That's work in progress, not production ready, obviously. With this config in place time machine will backup to the SMB share but excruciatingly slow in my experience. Anyway I turned on "Issues" in my forked repo so any followup discussion can go there.

**Comment by Strayer** [comment]
@gonewest818 Cool, thanks for the heads up! I didn't have time for this yet, but still plan to do TimeMachine in the next 2-3 weeks. Going to contribute my stuff there so we can maybe coordinate a pull request when 4.8 goes into alpine stable.

**Comment by bofm** [comment]
@Strayer @gonewest818 did you make TM work with samba 4.8?

**Comment by Strayer** [comment]
Not yet, though I want to (or rather need to) tackle this in the next two weeks.

Am 17. Juni 2018 11:02:54 MESZ schrieb bofm <notifications@github.com>:
