### ISSUE TITLE
Can I make a share public read/write?

### ISSUE THREAD

**Issue by phillijw** [dperson/samba#140]
I just want to share a drive and allow anyone to read/write. How complicated is it to do this?

**Comment by BelgarionNL** [comment]
would also love some help with this as I am a newbie in docker compose.

**Comment by w-flo** [comment]
Well, it's exactly what I'm doing and I wouldn't say it's that hard. With one caveat though, I was unable to make the share show up automatically, but that's not important for me and typing "\\\\hostname" into Windows Explorer or "smb://hostname" into nautilus connects to my shares successfully. I believe that is because Win 10 stopped *really* supporting the SMB1 protocol some time ago, which samba still uses through nmbd to advertise shares. I believe nautilus can still find SMB shares if a service like avahi is running on the samba machine and advertises the share, or maybe nautilus still supports the old nmbd way, not sure (I'm not using nmbd). Windows definitely needs the WS-Discovery method though, which is not supported by samba, unless you manually enable SMB1 or access an old SMB1 share within 15 days of installing Win10 or something – in that case SMB1 support is kept enabled.

So, in order to get the share(s) up and running, take a look at my docker-compose file for samba. I have 2 shares set up, one ("raid") uses a raid file system and the other one ("shared") is just plain old ext4 and risks getting lost when the hard drive dies. Using the "volumes" section, I mount the directories from the host into the container's "/shares" directory and use the subdirs of "/shares" for the samba config. See the dperson/samba README for details about the "-s" option.

The files in my share directories are mostly owned by uid / gid 1000, so I use the same for smbd to access/create files. You may want to use a different uid/gid combo, depending on how you organize your files.

Make sure the "-g" line is correct for your LAN interface names, or remove both "-g" lines to make samba bind to all interfaces available on the host machine (probably including any interfaces used for docker networks). "ip link" suggests my LAN interface is called "enp2s0", so I used "enp*", as wildcards are supported. "lo" is always required according to the docs. I'm not sure if mapping port 139 is really required.

I have this docker-compose.yml file in a directory "samba", and then all I needed to do was "docker-compose up -d" for the container to be created and started. So the only things involved are this simple file and the share directories on my host machine ("/path/on/host…" below). For updates, "docker-compose pull" and "docker-compose up -d" to throw away the old container (all the state is stored in the compose file and the mounted share directories) and create a new one should be enough when the image gets updated on dockerhub.

```version: '3.4'

services:
  samba:
    image: dperson/samba:latest
    command: >
      -w "WORKGROUP"
      -s "shared;/shares/shared;yes;no;yes;all;none;;comment1"
      -s "raid;/shares/raid;yes;no;yes;all;none;;comment2"
      -g "bind interfaces only = yes"
      -g "interfaces = lo enp*"
    environment:
      - USERID=1000
      - GROUPID=1000
    volumes:
      - /path/on/host/to/shared:/shares/shared
      - /path/on/host/to/raid:/shares/raid
    network_mode: host
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
```

So – thanks, dperson, it's a nice and easy to use image!

**Comment by phillijw** [comment]
I ended up using a command kind of like this:
```
docker run \
  -p 139:139 \
  -p 445:445 \
  -p 137:137/udp \
  -p 138:138/udp \
  -e TZ=CST6CDT \
  -v /media/myshare:/mount/myshare\
  -d \
  --name samba \
  --restart unless-stopped \
  dperson/samba \
  -n \
  -S \
  -g "map to guest = Bad User" \
  -s "myshare;/mount/myshare;yes;no;yes;all;none;;comment1"
```

This still did not allow me to log in as guest from Win10. I had to type in a username of "\" and no password for win10 to let me in. That seems pretty dumb but I'm not sure how to get around that.

**Comment by tataue** [comment]
add a command with user rock with password
```
docker run \
  -p 139:139 \
  -p 445:445 \
  -p 137:137/udp \
  -p 138:138/udp \
  -v $HOME/mnt/samba:/home/rock\
  --name samba dperson/samba \
  --restart unless-stopped \
  -n \
  -S \
  -g "map to guest = Bad User" \
  -g "netbios name  = yoyoStore" \
  -u "rock;rock-pass" \
  -s "xiaomi1;/home/rock/xiaomi1;yes;no;no;rock;rock;none;;comment1" \
  -s "xiaomi2;/home/rock/xiaomi2;yes;no;no;rock;rock;none;;comment2"
```
