### ISSUE TITLE
can the image when deployed authenticated file share connection requests using active directory

### ISSUE THREAD

**Issue by myusrn** [dperson/samba#177]
can the image when deployed authenticated file share connection requests using active directory?

**Comment by dperson** [comment]
I know that samba supports it, but you have to join the system to AD IIRC. It's more work / hassle because MS wants their license fees for every system that authenticates via AD. I don't have an AD system, nor want one, so haven't built in anything to the setup script about joining to a domain.

You can do so on your own however, there's a normal samba install available.

**Comment by hugoelopezp** [comment]
Were you guys ever able to make this work? I'd like to see if I can deploy a few of these docker containers across multiple Docker hosts with shared storage, as in a File server cluster. The only part I'm missing is integration with AD for authentication

**Comment by myusrn** [comment]
@hugoelopezp i don't recall ultimately doing a test to confirm it works with azure active directory authentication involved.
