### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by fabnavigator** [dperson/samba#194]
Hi,

I've been trying to get samba working in docker for quite a while now. I'm trying to share my "/home/fabnav/opt" folder as "docker". I used the example from your Wiki as a starting point. Please tell me what I'm doing wrong. 

docker run -it --name samba --restart "no" -p 139:139 -p 455:455 -p 137:137/udp -p 138:138/udp -v /home/fabnav/opt:/v_shared -d dperson/samba -s "docker;/v_shared" -n

**Comment by neil-bowers** [comment]
While I'm not the author, I can tell you that this error usually pops up when the image that you're using isn't compatible with your CPU architecture.

For example, you'll get this error if you try to use the `dperson/samba` image on a Raspberry Pi, which is `armvhf`, because this image expects a `x86` type CPU.

**Comment by fabnavigator** [comment]
Thank you. I'm sure that is the problem.

**Comment by dperson** [comment]
There are arm images, if you specify the `dperson/samba:aarch64` or `dperson/samba:armhf`.

**Comment by melikyuksel** [comment]
@dperson Should it not pull the correct image automatically?

**Comment by dperson** [comment]
@melikyuksel that's something outside of my control, it's handled by docker.
