### ISSUE TITLE
memory use

### ISSUE THREAD

**Issue by bingobob** [dperson/samba#202]
Just want to check this is expected / normal? Seems odd?

When I start the container memory use is about 10M.

I then transfer a load of large files from the server to my laptop.

Memory usage of the container goes to about 6 gig!

When the transfer is finished it doesn't go back to 10M without restarting the container?

**Comment by pho3nixf1re** [comment]
I'm pretty sure that I'm seeing this as well. If I leave the container running it eventually crashes the server (sometimes taking a few weeks, I don't use the network shares much). If I turn off the samba container the server never crashes. I have tried this on a RaspberryPI 3 B+ as well and the crashes happen much more frequently. Both because I used the shares there more and the memory on the PI is much smaller.

**Comment by banana-ben** [comment]
I'm not using this image currently, but I am using [willtho89/docker-samba-timemachine](https://github.com/willtho89/docker-samba-timemachine) which is loosely based off of this project and I experience the same memory issue. To work around it I limited the container to 512mb of memory by changing my docker-compose file from version 3 to version 2 and added a new line: `mem_limit: 512m`. I don't have any idea how much RAM it really needs but I don't have any performance issues at 512mb and am comfortable sacrificing that much memory to it so that's what I've left it at for now.

**Comment by dzubape** [comment]
> I'm not using this image currently, but I am using [willtho89/docker-samba-timemachine](https://github.com/willtho89/docker-samba-timemachine) which is loosely based off of this project and I experience the same memory issue. To work around it I limited the container to 512mb of memory by changing my docker-compose file from version 3 to version 2 and added a new line: `mem_limit: 512m`. I don't have any idea how much RAM it really needs but I don't have any performance issues at 512mb and am comfortable sacrificing that much memory to it so that's what I've left it at for now.

Hello, TravelinMax! Thnx a lot for your trick! What happend, if container reaches the limit? Does it restart? If so, is it a problem for copying huge files?

**Comment by TravelinMax** [comment]
@dzubape I tested it with some multi-gig files today and no restarts! I can't say for certain that Time Machine doesn't break large files into pieces before sending them over the network, but I've never noticed the container restart due to the RAM limit. Typically it quickly hits the 512mb limit once it starts seeing use and hovers between 500-512 for the life of the container ¯\\_(ツ)_/¯

**Comment by dperson** [comment]
I wasn't making much progress in tracking down what was going wrong. Thank you!

I've added an item to the troubleshooting section of the `README.md` for memory usage with your suggestion.
