### ISSUE TITLE
Empty Recycle Bin on a Schedule

### ISSUE THREAD

**Issue by adit-s** [dperson/samba#238]
Hello. Is there a way to set the recycle bin to empty deleted items after they have been in the .deleted folder for a selected period of time?
For example, set a variable so that items which were deleted 7 days ago (or whatever period) are automatically removed from the .deleted folder?

Thanks in advance.
Adit

**Comment by dperson** [comment]
No, not that I'm aware of.

**Comment by Waldorf3** [comment]
Was looking for the same. Since it appears to not exist I threw this simple bash script together, Stick it in root's daily cron to clear out .recycle folders.  I think it is probably simple enough to be self-explanatory - just adjust SMBFOLDERS to the root folders of your SMB shares and OLDAGE to how many days until deletion.

```
#!/bin/bash

SMBFOLDERS="/homes /media"
OLDAGE=30

for RECBIN in $(find ${SMBFOLDERS} -type d -name .recycle -print)
do
  for OLDSTUFF in $(find ${RECBIN} -mtime +${OLDAGE} -print)
  do
    [ ${OLDSTUFF} != ${RECBIN} ] && rm -rf $OLDSTUFF >/dev/null 2>&1
  done
done
```
