### ISSUE TITLE
Error: unknown shorthand flag: 's' in -s

### ISSUE THREAD

**Issue by DjangoFR** [dperson/samba#243]
$ sudo docker run -it --name samba -p 139:139 -p 445:445 -u "user;samba" -v /tmp/samba:/mount -s "/tmp/samba;/share;guest;readonly" -d dperson/samba -p

unknown shorthand flag: 's' in -s
See 'docker run --help'.

**Comment by dperson** [comment]
@DjangoFR the issue is that there are command line arguments that go to the docker daemon, and there are command line arguments that go to the entry point script that's inside the container to set things up for you. Neither one can interpret the other's arguments. So the following, as well as all of the documented options in the `README.md` (which go to the script in the container) have to go after the `dperson/samba`:
```
-u
-s
```
So your particular command line should read:
```
sudo docker run -it --name samba -p 139:139 -p 445:445 -v /tmp/samba:/mount -d dperson/samba -p -s "/tmp/samba;/share;guest;readonly" -u "user;samba" 
```

**Comment by jsglazer** [comment]
Just wanted to confirm that moving -d line up resolved the problem.  thanks DjangoFR
