### ISSUE TITLE
Guest Write Access Not Possible

### ISSUE THREAD

**Issue by utdrmac** [dperson/samba#270]
Trying to create a share which is writeable by all guests.

`-s "Guest_Backup;/backup;yes;no;yes;all;none;all"`

Does not appear to work. Using MacOS, login to share as Guest and cannot write to said share.

**Comment by janstuemmel** [comment]
this is about unix file permissions. The smb user in the image has the id=100, the first user on your mac (normally you) has 1000. 

When you create a file via smb then smb wants to create it with id=100, but your share has eventually only write permissions with id=1000. Check that with `ls -n /mount`.

How to fix ? A quick and dirty hack would be changing the smbuser id to 1000 as well as the group, i did this because i am the only one using my share:

Create a `Dockerfile` next to the `docker-compose.yml`:

```dockerfile
FROM dperson/samba

RUN groupmod -g 1000 smb && usermod -u 1000 smbuser
```
In your `docker-compose.yml` change following:

```diff
version: "3"  
services:  
  samba:
    restart: always
+   build: .
-   image: dperson/samba
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    command: 
      - "-p"
      - "-n"
      - "-s" 
      - "data;/mount;yes;no;yes;all"
      - "-w WORKGROUP"
    volumes:  
      - /path/to/folder:/mount
```

**Comment by dperson** [comment]
It could well be a permission issue as well, the `-p` argument to the startup will set permissions. But the setting that is likely at the root is in the global section `map to guest`, to override it check the documentation for the `-g` argument and the samba documentation for `map to guest`.
