### ISSUE TITLE
README should mention about user creation, password sync, ACLS etc.

### ISSUE THREAD

**Issue by victorhooi** [dperson/samba#303]
This is a seriously awesome project =) - excited to get this working.

I'm a little confused about the user account side of things though.

Normally in SAMBA, you need the user created as a local Linux user, then you use `smbpasswd` to create a matching Samba user. And then I believe there are options to keep the two passwords in sync.

My question is - how does this work with this Samba Docker container?

Do we still need to create the underlying local Linux user? And will this be exposed somehow into the Docker container? And how does password syncing work?

I think this should be documented in the README somewhere if possible.

And how does this work in terms of permissions for the mountpoint and Samba share itself?

**Comment by dperson** [comment]
No users interact with nor are they needed for those inside the container. That's the point of containers. The `README.md` already covers how to create users. As there is no interaction with users outside the container, there is no sync that can / will take place.

Because there is no sync (nor should a container be allowed to manage users on the host) and the container was made to make creating shares simple, the auto configured system will store / access all files as a single user (see `USERID` and `GROUPID` to manage it) when sharing the contents of any volumes.

**Comment by victorhooi** [comment]
Thanks for getting back!

Hmm - ok - so the users specified with `-u` exist only within the Docker container, right? But if you want to password protect a share, this is where you do it.

And you need to set the environment variables USERIR and GROUPID - and this will affect what user context is used to access or create new files on the host?

And I assume the user running the Docker container will need read/write access to the folder you are sharing?

How does the `-p` option play into all of this?

**Comment by dperson** [comment]
Yes, users are only in the container.

`USERID` and `GROUPID` are those used to access the files on the host.

The docker server runs as root, so unless MAC (Manditory Access Control) limits root, if you can tell docker what to do, you have access (this is by design in docker).

The `-p` option has the container set the ownership to match the `USERID` and `GROUPID` (or the defaults), so that samba will have access to the files / directories.

**Comment by LexxM3** [comment]
Apologies on resurrecting an old issue/discussion, but I haven't (so far) found a good discussion and suggestion on a strongly related issue ...

While `-u "user;password"` IS a very simple approach, it requires the password to be in the clear on the host. Is there a suggested way to setup and manage Samba users in the container where the password can be properly encrypted or hashed at all times?

Of course one can setup users inside the container using facilities described by the OP, but the real issue then is how to persist those users between container kill/run/reboot cycles?
