### ISSUE TITLE
How do i make a home directory?

### ISSUE THREAD

**Issue by vermium** [dperson/samba#337]
i wanna make a [homes] share how do i do? @dperson

**Comment by stefanheinrichsen** [comment]
I use in my compose file:

volumes:
[...]
  - /home/:/mount/home

command: >
[...]
 -s "homes;/mount/home/%U;yes;no;no;all;Home Verzeichnisse"

However did not tests this in depth. Especially because I currently have only one user... so not sure if new files are created correctly (owner and permission) and if users are seperated correctly.

**Comment by stefanheinrichsen** [comment]
Short addition: No, file owner is not correct... Guess this was the reason for https://github.com/dperson/samba/pull/134
Not sure if this is really in the samba.sh file though. Seems not to me...

**Comment by vermium** [comment]
Thanks!
