### ISSUE TITLE
Cant add Files to shared directory

### ISSUE THREAD

**Issue by lukasPF** [dperson/samba#343]
Hi, im running Samba on my Raspberry Pi 3b (Raspiam Buster) with docker. I started The Container with the following command:
`Sudo docker Run -it -p 139:139 -p 445:445 -d dperson/Samba -p -u "Lukas;123456789" -s "Public;/mnt"`
I See The folder Public and can Open IT but cant add Amy files

**Comment by g8ry** [comment]
I'm guessing .......

Thats because only root can write to /mnt within your container.
Do you need to add a volume to share ?

docker Run -it -p 139:139 -p 445:445 -d \
-v "/my_host_shared:/public" \
-s "/public:/public" \
dperson/Samba

the -v command will mount your '/my_host_shared' directory within the container as /public
the -s command will share that directory.

If you log into your container, only root can write to /mnt (I think)

**Comment by lukasPF** [comment]
Im not sure if I understood you correctly but i can't add -v unknonw option
