### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by g8tguy** [dperson/samba#48]
I create a container with the `root;root;0;0` key in order to assign `ROOT` user and `ROOT` group the new files. 
```
docker run --rm -itd --net=host --name samba -v volume:/data/volume dperson/samba -n -u "root;root;0;0" -s "docker;/data;yes;no;no;all;root"
```

but when I create a file on a share, the permissions are
```
-rw-rw-r-- 1 root users    0 Mar 21 21:30 file.txt
```
how can I set the group to `ROOT` ?

Thank!

**Comment by dperson** [comment]
This container is a way to quickly and easily setup a simple share. All files are setup to be owned by one user and group (less to synchronize with the docker host). To set the UID and GID set the `USERID` and `GROUPID` environment variables. Just set them both to `0` and you should get the results that you want. Hope that helps.

**Comment by g8tguy** [comment]
It worked! I just thought `-e GROUPID=0 -e USERID=0 ` is equal to `-u "root;root;0;0"`

**Comment by htkoca** [comment]
Wait I'm curious: what exactly is the dirrence between the userid and groupid in `-u` and in the environment variables `USERID` and `GROUPID`?

**Comment by dperson** [comment]
@htkoca sorry for the slow reply, I was out of town on vacation.

The `-u` flag will create a user on the system, for simple authentication needs.

Because this container is designed to be a simple and easy way to share a directory of files, it skips many more advanced features of samba and AD. All file access takes place as the `smbuser` user and group `users`. The `USERID` and `GROUPID` environment variables will be used for the `smbuser` and `users` user/group in the container.

This prevents most permission issues, also as users created in the container won't be created on the host running docker, there are fewer random IDs to deal with there. If you set `USERID` and `GROUPID` to a valid user on the docker server, the files will be owned by that user/group.
