### ISSUE TITLE
Can't connected by linux client

### ISSUE THREAD

**Issue by chtbof** [dperson/samba#71]
Can't connected by linux client, but the windows client OK

**Comment by dperson** [comment]
First, without any logs / error messages I have no idea what's going wrong.

Do you have basic connectivity? Can you ping the host from the Linux box?

**Comment by chtbof** [comment]
Thanks for your replay.
I using the the script to deploy a container for remote linux server
sudo docker run -it --name sambax1 -p 137:137/udp -p 138:138/udp -p 139:139
-p 445:445 -d -v /home/docker:/home dperson/samba \
            -u "x1;P#1234" \
            -s "x1;/home;yes;no;no;x1;x1;x1"

The windows client is working perfect.
but the linux client show
[image: 內置圖片 1]

When I using the samba server in the host , both linux and windows clients
working good.

thanks for your time

Chtsai

2017-08-29 22:46 GMT+08:00 David Personette <notifications@github.com>:

**Comment by dperson** [comment]
Whatever Image you tried to attach to the email didn't make it to the github issue...

**Comment by chtbof** [comment]
Show
"Timeout on server"

**Comment by dperson** [comment]
When you get the error message, are you connecting with `smbclient`, `mount -t smb` or `mount -t cifs`, using a desktop GUI file manager, etc?

Are you browsing to it (IE file manager) or providing the host name of the server running the docker container?

**Comment by user5145** [comment]
The same problem here.
-S parameter (disable minimum smb2) is necessary for me to connect from linux, otherwise logs (docker logs command) will output "no protocol supported !". If i add -S, linux will be able to log without password to any share. I have used nautilus with gnome. Host name is CentOS Linux release 7.3.1611 (Core) with selinux.

To run container I have used this (:Z in volume is for selinux):
#!/bin/bash
docker run --name samba --restart=on-failure:10 \
             -v /home/share:/home/share:Z \
             -v /home/private:/home/private:Z \
             -it -p 137:137/udp -p 138:138/udp -p 139:139 -p 445:445 -m 1024M -d dperson/samba \
             -u "server;123" \
             -s "private;/home/private;yes;no;no;server" \
             -s "public;/home/share;yes;no;yes" \
             -n

I hope it's helpful for this case.
